id: AE286572B
title: The Confession of Downfalls from the Great Compassionate One’s Lotus Uṣṇīṣa
type: translation
pechas:
- I732B15C5
- I8A384370
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:32:27.979415
  last_modified_at: 2023-01-04 11:32:27.979424
  collections:
  - Chokgyur Dechen Lingpa
  - Works of Tibetan Masters
alignment_to_base:
  I732B15C5/A0A7: F37A
  I8A384370/FCE9: F37A
